### ISSUE TITLE
Use with Shared Storage API + Origin Trial

### ISSUE THREAD

**Issue by SpaceGnome** [patcg-individual-drafts/private-aggregation-api#1]
I'm glad to see https://github.com/alexmturner/private-aggregation-api! I'm hoping to be able to use this in conjunction with https://github.com/pythagoraskitty/shared-storage for some fraud & abuse use cases to replace some 3P cookie functionality. 

I do also want to +1 https://github.com/alexmturner/private-aggregation-api#authentication-and-data-integrity as that's going to be important that we maintain integrity of the aggregated data.

Do we expect an Origin Trial soon with the Private Aggregation and Shared Storage APIs so we have enough time to start experimenting with them?

Thanks!

**Comment by alexmturner** [comment]
Glad to hear the interest in testing out the APIs! We are working on the implementation and getting the APIs ready for an Origin Trial, but the timeline is still TBD.

**Comment by SpaceGnome** [comment]
Thanks!

**Comment by rmirisola** [comment]
Having this API would be very valuable to power R&F use cases, as discussed in https://github.com/patcg/meetings/issues/12

Hope it can be come available soon!

**Comment by SpaceGnome** [comment]
Is there an update on this?

**Comment by alexmturner** [comment]
Hi, the Private Aggregation API is currently available in an Origin Trial (along with Shared Storage). This has rolled out to 50% of Chrome Canary, Dev and Beta users.

Further details are available in our [developer docs](https://developer.chrome.com/docs/privacy-sandbox/private-aggregation/). I'd also recommend you join the [Shared Storage announcements mailing list](https://groups.google.com/a/chromium.org/g/shared-storage-api-announcements) to be notified of any updates.

Please let us know if you have any questions!
