### ISSUE TITLE
Debug Mode Availability for Latency Stats?

### ISSUE THREAD

**Issue by maleangrubb** [patcg-individual-drafts/private-aggregation-api#104]
Hello,

Wanted to inquire when debug mode for the Private Aggregation API would be available for latency-stats? Is this something that is planned in the near term?

Thank you!

**Comment by alexmturner** [comment]
Please see the response here: https://github.com/WICG/turtledove/issues/709#issuecomment-1747396717

**Comment by alexmturner** [comment]
Hi @maleangrubb, just drawing attention to our email that support for this is now live in M123: https://groups.google.com/a/chromium.org/g/fledge-api-announce/c/hgtqi4m-Wxs.

**Comment by maleangrubb** [comment]
I believe there may be a bug in the impl of this feature. Some new fields introduced for this feature in the `auctionConfig` (`auctionReportBuyerKeys`, `auctionReportBuyers`, `auctionReportBuyerDebugModeConfig`) require bigints. However, based on some failing testing on our end, it appears the `auctionConfig` is being stringified sometime during the `navigator.runAdAuction()` call. `JSON.stringify()` does not support bigint conversion without a bit of extra parsing work...

Sample Error: 
```
TypeError: Do not know how to serialize a BigInt
             at JSON.stringify (<anonymous>)
             at navigator.runAdAuction
```

**Comment by maleangrubb** [comment]
Alex, I believe there may potentially be a bug in the impl of this feature.
Have raised the issue at
https://github.com/patcg-individual-drafts/private-aggregation-api/issues/121
.

**Comment by maleangrubb** [comment]
Issues closed & resolved.
