### ISSUE TITLE
aggregation_coordinator_origin underspecified (underdefined??)

### ISSUE THREAD

**Issue by miketaylr** [patcg-individual-drafts/private-aggregation-api#107]
In https://patcg-individual-drafts.github.io/private-aggregation-api/#serializing-reports `aggregation_coordinator_origin` is defined as an origin. It would be nicer if it was more descriptive and said something like it's the origin that corresponds to https://wicg.github.io/attribution-reporting-api/#aggregation-coordinator (and links out to the ARA).

**Comment by alexmturner** [comment]
I think this should be resolved by the full aggregation coordinator choice spec PR (#106). The current definition is a temporary change to reflect the state before Private Aggregation launches this feature.

**Comment by alexmturner** [comment]
Closing now that the full PR has landed
