### ISSUE TITLE
Enabling Debug Reports in Private Aggregation API in Mode B.

### ISSUE THREAD

**Issue by michal-kalisz** [patcg-individual-drafts/private-aggregation-api#110]
Hi, 

Mode B is about to start, for which we have all been preparing for quite some time. This will be a great opportunity to check how well the Protected Audience operates in an environment without 3rd party cookies. Not only from a technical perspective but also from operational and business perspectives. Thanks to event-level reporting, we can gather information about campaign performance. A much greater challenge is collecting statistics on how auctions are conducted. Two very powerful tools serve this purpose:

- `forDebuggingOnly`
- `Private Aggregation API`

The first one will be available in Mode B, as per https://github.com/WICG/turtledove/issues/632#. Simultaneously, the Private Aggregation API is the ultimate solution, and it's worthwhile to start preparing for its use. However, as far as I understand, debug reports will not be available with the disabling of third-party cookies.

Of course, ultimately, debug reports will not be available for privacy reasons, but during Mode B testing, their absence presents a significant obstacle to properly monitoring campaigns.

Let's summarize a few facts:

1. In Mode B, there will be 0.75% of Chrome users with Protected Audience enabled (Private Aggregation API as well) and 3rd party cookies disabled.
2. We have a limited number of reports that a user can send (AFAIK the queue size is 1000), so we limit ourselves to sending reports at the bidding level only for 1% of bids.
3. The number of users signing up for the Interest Group varies (from smaller to very large advertisers).
4. Considering the scale from points 1-3 and the fact that we have budget-related limitations: budget L1 on the browser side (2^16 per 10 minutes, 2^20 per day) and the fact that there is noise imposed on the Aggregation Service side, 
I would like to explore potential solutions to the above problems:
   - Enabling debug reports for Mode B
   or
   - Increasing the L1 budget for reporting origin site for Mode B.

Bests,
Michal

**Comment by menonasha** [comment]
Appreciate the feedback here. We are looking into possible solutions but do want to flag that on enabling debug reports, we would need to do so in the middle of Mode B since it has already started. Additionally this could only be a short term solution as ultimately debug reports will need to be tied to third party cookies long term and cannot be available for privacy reasons, as you have cited.

**Comment by menonasha** [comment]
hi @michal-kalisz we are moving forward with allowing debug mode in Mode B. This eligibility is changing in M121 Beta at 50% of Mode B traffic starting on 1/31. We will provide notice before ramping up to Stable.

**Comment by alexmturner** [comment]
Hi, as you've hopefully seen, this is now fully ramped up on M121+ (https://groups.google.com/a/chromium.org/g/fledge-api-announce/c/LtdKPzOdGi8)
