### ISSUE TITLE
FLEDGE integration

### ISSUE THREAD

**Issue by jonasz** [patcg-individual-drafts/private-aggregation-api#12]
Hi Alex,

I am very happy to see the Private Aggregation API [Intent to Experiment](https://groups.google.com/a/chromium.org/g/blink-dev/c/576sXtXNeCA/m/mGBpw14WBQAJ). We're looking forward to test it with FLEDGE.

The I2E is planned for M107, which is very soon ([link](https://chromiumdash.appspot.com/schedule)), and I was wondering if you could shed some more light on the planned FLEDGE integration.

More specifically, I was wondering, will it be possible to generate the histogram reports within generateBid, and only actually send them upon a specific future event? (E.g. winning the auction / showing the impression / user clicking the ad.) Please see https://github.com/WICG/turtledove/issues/177#issue-888048707 for additional context.

Best regards
Jonasz

**Comment by alexmturner** [comment]
Hi Jonasz, sorry for missing this! I hope you've seen the proposal we've since published: https://github.com/WICG/turtledove/blob/main/FLEDGE_extended_PA_reporting.md

**Comment by jonasz** [comment]
Hi Alex, sure, the update anrwers my questions, thanks!
