### ISSUE TITLE
Potential Bug in the debug mode latency stats implementation

### ISSUE THREAD

**Issue by maleangrubb** [patcg-individual-drafts/private-aggregation-api#121]
I believe there may be a bug in the impl of debug mode for PA API Private Aggregation latency stats.

Some new fields introduced for this feature in the `auctionConfig` (`auctionReportBuyerKeys`, `auctionReportBuyers`, `auctionReportBuyerDebugModeConfig`) require bigints. However, based on some failing testing on our end, it appears the `auctionConfig` is being stringified sometime during the `navigator.runAdAuction()` call. `JSON.stringify()` does not support bigint conversion without a bit of extra parsing work...

Sample Error: 
```
TypeError: Do not know how to serialize a BigInt
             at JSON.stringify (<anonymous>)
             at navigator.runAdAuction
```

**Comment by alexmturner** [comment]
Hey @maleangrubb, thanks for filing the issue. We do have some end-to-end tests that don't seem to hit this problem. Would you be able to send a minimal example that reproduces this issue?

One important thing to note is that the Protected Audience API requires that "All fields that accept arbitrary metadata objects ... must be JSON-serializable." (More detail is in the [explainer](https://github.com/WICG/turtledove/blob/main/FLEDGE.md).) So, it is currently expected that you'll hit an error if you put a bigint into those _other_ fields (e.g. the `auctionSignals`).

**Comment by alexmturner** [comment]
And, just to confirm, when you run that exact config, you get the error? My local testing (on a random page) doesn't show that config causing an error.

**Comment by maleangrubb** [comment]
Alex, I figured out the issue. Not a bug on Chrome's end, the stack trace just made it appear that way. Thanks for helping look into this with testing on your end!
