### ISSUE TITLE
Is it possible to send a negative value in contributeToHistogram()?

### ISSUE THREAD

**Issue by romanych** [patcg-individual-drafts/private-aggregation-api#125]
Imagine we sent a contribution to the histogram that the user made a purchase. The next day, the user cancelled her purchase. Is it possible to send a negative value so that it will be deducted in the summary report?

**Comment by rushilw-google** [comment]
Hi @romanych, Private Aggregation API does not support negative value contributions. You could use a new key for cancellations and subtract the aggregate value from a purchase summary report. However, both reports will be noised by the Aggregation Service separately before you can perform the subtraction on your side.

While we could theoretically support negative values, it might not solve this use case, as cancellations could easily fall in different batches for Aggregation Service processing. Note that negative values would still need to consume positive contribution budget even if they cancel out a previous contribution.

**Comment by romanych** [comment]
Got it, @rushilw-google, for your answer.
