### ISSUE TITLE
Meeting: Supporting Reach Measurement

### ISSUE THREAD

**Issue by alexmturner** [patcg-individual-drafts/private-aggregation-api#19]
We will hold a meeting in February on how the Private Aggregation API could best support the Reach use case. Additional meetings will be scheduled as needed.

We plan to discuss the [recent proposals](https://github.com/patcg-individual-drafts/private-aggregation-api/issues/17) to extend the API to support more advanced reach reporting. We also hope to hear feedback from other stakeholders on these proposals and, more generally, what functionality is considered critical for supporting reach measurement.

We will meet for one hour starting at **Wednesday 15 February at 4 pm Eastern Time** (= 9 pm UTC = 10 pm Paris = 1 pm California).
The call will take place on Google Meet.
Video call link: https://meet.google.com/jsz-vnjk-dsr
Or dial: ‪(US) +1 253-289-6828‬ PIN: ‪185 375 697 81‬#
More phone numbers: https://tel.meet/jsz-vnjk-dsr?pin=6836240560245

Agenda proposals, attendance records, notes will happen in this Google Doc:
https://docs.google.com/document/d/1j8gWNkOvIRrI1vi2vg3Pv13hjKf-i7bugiEUZsrU4UU/edit?usp=sharing

For a speaker queue, we will use the Google Meet "Raise My Hand" feature.

If you want to participate in the call, please make sure you join the PATCG: [w3.org/community/patcg](https://www.w3.org/community/patcg/).

**Comment by EvgSkv** [comment]
Alex, thanks for your response!
Time time of Wednesday 15th of February at 2pm Eastern (= 11am Pacific) time works for me.
I am looking forward to the discussion!

**Comment by alexmturner** [comment]
Great, thanks! Let's lock in that time then (unless we hear differently from anyone else) and I'll provide further details (meeting link, doc) soon.

**Comment by alexmturner** [comment]
Actually sorry for the flip flopping, but would 4pm Eastern (=1 pm Pacific) work? (If not, we can leave it at the original time.) Thanks!

**Comment by dmdabbs** [comment]
>would 4pm Eastern (=1 pm Pacific) work?
WFM 👍

**Comment by EvgSkv** [comment]
Yes, 1pm on Wednesday 15th of February works for me.

**Comment by alexmturner** [comment]
Awesome, thanks both. Let's go with that then!

**Comment by EvgSkv** [comment]
@alexmturner Great! But how do I access the meeting?

**Comment by dmdabbs** [comment]
This will surely be a meeting for more than the three of us.
You will publicise on one of the developer mailing lists, yes?
Possibly [https://groups.google.com/a/chromium.org/g/attribution-reporting-api-dev](https://groups.google.com/a/chromium.org/g/attribution-reporting-api-dev).
Does PAA have its own list?

**Comment by alexmturner** [comment]
@dmdabbs Thanks for the reminder, we've just sent a notice out on the [Shared Storage announcements list](https://groups.google.com/u/1/a/chromium.org/g/shared-storage-api-announcements).

@EvgSkv Meeting details have been added to the issue description.
