### ISSUE TITLE
Clarify reporting origin

### ISSUE THREAD

**Issue by alois-bissuel** [patcg-individual-drafts/private-aggregation-api#29]
Hello,

I am trying to understand how the reporting origin is defined, so as to know on which domain to host the well-known endpoints for collecting the data.
For Fledge reports, I guess this is simply defined from the IG owner or the bidding URL (not a Fledge expert, so pardon my approximations).
For Shared Storage, I have no idea which domain is used. Is it the origin of the script?

Thanks a lot!

**Comment by alexmturner** [comment]
Hi!

The reporting origin is always the script origin of the Private Aggregation caller. So: for FLEDGE bidders, that should be the IG owner; for FLEDGE sellers, that should be the origin that calls `runAdAuction()`; and for Shared Storage, that should be the origin that calls `sharedStorage.run()` or `.selectURL()`.
