### ISSUE TITLE
Use for frequency capping model calibration

### ISSUE THREAD

**Issue by zihexutony** [patcg-individual-drafts/private-aggregation-api#3]
Thanks for sharing the proposal of Privacy Aggregation API https://github.com/alexmturner/private-aggregation-api. After going through the proposal, I think it would be great if it could support the use case of frequency capping model calibration. There was a aggregated reporting proposal and an [example use case](https://github.com/csharrison/aggregate-reporting-api#advanced-example-calibrating-a-frequency-capping-model) for this, but it seems like that proposal hasn't been updated for a while and I guess it might be out-of-date. However, we are still looking for a solution to calibrate the frequency capping model and I think Privacy Aggregation API could be helpful. 

I have learned that the [Shared Storage API](https://developer.chrome.com/docs/privacy-sandbox/shared-storage/#url-selection) in the Chrome Privacy Sandbox can be used to enforce frequency capping in browser. However, if we can use the Privacy Aggregation API to generate a ratio (like **_# ads per user in domain X_** / **_total # ads across all domains for users visited X_**) to adjust the global cap, the adjusted cap can be used across different browsers. 

Does it sound like a use case that the Privacy Aggregation API will support? Thanks for shedding light on this.

**Comment by alexmturner** [comment]
Thanks for letting us know about your use case! I'm not sure about all the details, but something like this seems possible under the current designs. Two considerations that come to mind:
- You would need to specify a fixed mapping of domains to keys ahead of time (this could use the modulo hash idea in the old proposal you linked)
- If you don't want to measure an average of # ads per user -- i.e. you'd like a different statistic or a distribution -- you may need to wait until after your measurement period is over before sending your report.
