### ISSUE TITLE
Consider reducing maximum number of contributions per report

### ISSUE THREAD

**Issue by alexmturner** [patcg-individual-drafts/private-aggregation-api#32]
We plan to [pad the encrypted payload](https://github.com/patcg-individual-drafts/private-aggregation-api#padding), which will increase the size of the payload. To mitigate this size increase, we're considering reducing the number of contributions allowed in each report (e.g. from 50 to 20).

Note also that currently, any additional contributions would be dropped, but we could also consider allowing batching of contributions into multiple reports if this maximum value is limiting. Please let us know if you have any thoughts!

**Comment by csharrison** [comment]
How large will the padded payload be?

**Comment by alexmturner** [comment]
The encrypted payload currently has size around 76 + #contributions*36 bytes, i.e. ~1.9 kB for 50 contributions and ~800 B for 20 contributions.

We also might be able to compress our representation (eliminating the "bucket" and "value" strings) to get the per-contribution factor down to 21 or 23 bytes, i.e. ~1.1 or ~1.2 kB for 50 contributions and ~500 B for 20.
