### ISSUE TITLE
Fetch based design as a considered alternative

### ISSUE THREAD

**Issue by yoavweiss** [patcg-individual-drafts/private-aggregation-api#42]
When working on [Pending Beacon](https://github.com/WICG/pending-beacon), we got [feedback](https://github.com/WICG/pending-beacon/issues/70) that the design should be as close to `fetch()` as possible. There are parallels here, so I'm filing this issue as means to think through the implications of that alternative design.

A few differences between fetch()/PendingBeacon and this API:
* It's an anti-goal here to give the developer any control over when reports are being sent or knowledge that they were sent
* The reports are sent to very specific end-points, and not to any arbitrary reporting end-point
* The report's input is extremely specific (an array of [PAHistogramContribution](https://patcg-individual-drafts.github.io/private-aggregation-api/#dictdef-pahistogramcontribution)s), and not amenable to `fetch()`'s general purpose sending
* There's no concept of a response (even though that's similar for PendingBeacon)

Given all the above, I think it makes sense to not try to align this with `fetch()`. At the same time, it's worthwhile to document the reasoning.

**Comment by yoavweiss** [comment]
Talking to @noamr, another potential reason why this should be `fetch()` is that this API is to be called from environments where a "regular" fetch() shouldn't be available.

**Comment by noamr** [comment]
Yea this seems like an API more related to shared storage worklets and FLEDGE rather than having anything to do with general-purpose fetching.
