### ISSUE TITLE
`sendHistogramReport` is not an accurate name

### ISSUE THREAD

**Issue by yoavweiss** [patcg-individual-drafts/private-aggregation-api#44]
IIUC, [`sendHistogramReport`](https://patcg-individual-drafts.github.io/private-aggregation-api/#dom-privateaggregation-sendhistogramreport) doesn't in fact send a report, but queues up a (single) [PAHistogramContribution](https://patcg-individual-drafts.github.io/private-aggregation-api/#dictdef-pahistogramcontribution).

As such, we may want to consider renaming it, e.g. to `aggregateHistogramContribution` or `appendHistogramContribution`.

Aside: would it make sense to enable it to get an array of `PAHistogramContribution`s as input?

**Comment by alexmturner** [comment]
Changing makes definitely sense. Wdyt about `contributeToHistogram()`? This would avoid having to make it plural if we allow an array as input as well.

**Comment by alexmturner** [comment]
(Leaving open for the array suggestion)

**Comment by xottabut** [comment]
Just found the next information about the batching:
https://github.com/patcg-individual-drafts/private-aggregation-api#reducing-volume-by-batching

This is something that would work for us. The only concern for me is truncating to the 20 reports per batch, another proposed option with splitting bigger batches into few requests each with 20 reports max per one request looks better. 

Is there any information what is the status of this proposal? Will it be implemented?

**Comment by alexmturner** [comment]
Hi @xottabut! Sorry for the delay in responding.

Yes, as you saw, our current design involves consolidating/batching any contributions in a "batching scope" together into one report. We're still considering allowing an array to be passed to `contributeToHistogram()`, but this would just be syntactic sugar -- the effects would be identical to multiple calls each with one contribution.

This batching plan is currently implemented in Chrome and available under an Origin Trial. You can find some developer documentation here (although I don't believe it discusses this batching): https://developer.chrome.com/docs/privacy-sandbox/private-aggregation/. You can also find some more discussion of the design here: https://github.com/patcg-individual-drafts/private-aggregation-api/issues/32. But basically, the limit of 20 came to mitigate the size increase that will be introduced with padding.

However, we're definitely looking feedback on the design, for example about:
- the appropriate value for the maximum number of contributions per report
- the appropriate behavior if there are more contributions than that value

It sounds like if we moved from truncation to splitting the contributions into multiple reports each with 20 (or fewer) contributions, that would work for you -- is that correct?

Can you also share more details around your specific use case?

Thanks for the feedback!
Alex

**Comment by yoavweiss** [comment]
I opened #70 to tackle the "should we accept an array of contributions" question.
@xottabut - If there are still open questions around batching, I think it'd be better to open a new issue specific to those questions.

Otherwise, I think we can close this to avoid confusion, as the OP issue was resolved with #48
