### ISSUE TITLE
Consider tying `enableDebugMode()` availability to third-party cookie eligibility

### ISSUE THREAD

**Issue by alexmturner** [patcg-individual-drafts/private-aggregation-api#57]
This would ensure parity with what is available through cookies and allow for the temporary debugging mechanism to 'automatically' be removed when third-party cookies are.

**Comment by alexmturner** [comment]
Closing as this has been implemented

**Comment by nikijohnson4** [comment]
Thanks for the update

**Comment by a2425rdl** [comment]
good
