### ISSUE TITLE
What is a delay after which report is sent?

### ISSUE THREAD

**Issue by xottabut** [patcg-individual-drafts/private-aggregation-api#77]
Hi Chrome Team, 

Could you please clarify what is the delay for Private Aggregation API after which the report is sent?
I see it was changed for aggregatable reports to 0-10 minutes: https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#aggregatable-reports

For Private Aggregation API it is not specified in this or shared storage repository. 
On the chrome developer portal it is said up to 1 hour. Do aggregatable report have different delay for Private Aggregation API and Attribution API? 

Thanks,
Anatolii

**Comment by menonasha** [comment]
Hi Anatolli,

Yes there is a random delay of up to an hour for the Private Aggregation API. There is a potential path to reducing this delay if a timeout is imposed in the Shared Storage operation, as detailed in the report verification explainer: https://github.com/patcg-individual-drafts/private-aggregation-api/blob/main/report_verification.md#reduced-delay 

Thanks
Asha

**Comment by xottabut** [comment]
Thank you Asha for your response. 
I would keep this issue open until its 100% clear whether the delays will be changed to 1-5 minutes or kept as it is. This fact impacts the design, implementation and the way how output domain file is formed. So, I have the next two questions:
1. Is there any estimates when decision about the delay will be made?
2. Is there any open discussion I missed about this topic?

Thank you again,
Anatolii

**Comment by alexmturner** [comment]
Hi Anatolii,
We're tracking the possible reduction in issue #80. Note that this would only apply to reports with a context ID specified.
1. We're currently waiting on Shared Storage to implement a timeout, but we do plan to implement a delay reduction after that's complete.
2. As I mentioned above, issue #80 is where we're tracking this, but there hasn't been much discussion there.
3. It is between 10 and 60 minutes currently.

Thanks!
Alex
