### ISSUE TITLE
Consider reducing the delay for reports with a context ID

### ISSUE THREAD

**Issue by alexmturner** [patcg-individual-drafts/private-aggregation-api#80]
It may be possible to reduce the delay of reports sent with a context ID, see [here](https://github.com/patcg-individual-drafts/private-aggregation-api/blob/main/report_verification.md#reduced-delay).

While this change is web visible, the existing randomized delays mean that reliance on reports arriving at particular times is not currently possible. So, this should not be breaking.

**Comment by xottabut** [comment]
Hi Alex!

If context id allows associating events with the encrypted aggregatable reports then this already kills the idea of the delay to make this association hard/impossible. Any clients can just onboard context id. Does delay still make sense for reports without context id? Or I am missing something?

Thanks,
Anatolii

**Comment by alexmturner** [comment]
Hi Anatolii, you're correct -- that's why we have this as a proposal. There are some complications, but nothing too concerning (e.g. we don't want the exact delay to leak any info e.g. through Shared Storage running time so we need a timeout).
